/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Arquivo.java
 *
 * Created on 19/05/2012, 21:31:29
 */
package Igráfica;

import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.UIManager;
import moveisdecor.TransfArquivo;
import moveisdecor.Unicast;

public class Arquivo extends javax.swing.JFrame {

    ChatPrivate priv;

    /** Creates new form Arquivo */
    public Arquivo(ChatPrivate priv) throws Exception, ClassNotFoundException {
        this.priv = priv;

        UIManager.setLookAndFeel(//muda a aparência
                "com.sun.java.swing.plaf.windows.WindowsLookAndFeel");


        initComponents();


        getArquivo();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chooser = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        chooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(chooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooserActionPerformed
    }//GEN-LAST:event_chooserActionPerformed

    public void getArquivo() throws IOException, Exception {
        String caminho = null;
//pega o arquivo para enviar
        //  JFileChooser chooser = new JFileChooser();       
        int returnVal = chooser.showOpenDialog(null);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            //System.out.println("You chose to open this file: " +    
            //   chooser.getSelectedFile().getAbsolutePath());    
            File arq = chooser.getSelectedFile().getAbsoluteFile();

            caminho = arq.getPath();
            // >=> Só isso  
            String IP = priv.getIP();
            TransfArquivo.Envia(caminho, arq.getName(), IP); //envia o arquivo para IP correto

            Unicast uni = new Unicast(priv);
            uni.UnicastEnvia("Você recebeu o arquivo " + arq.getName(), IP);
            priv.setMsg("O arquivo " + arq.getName() + " foi enviado!!");
        }

        // return  caminho;     
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser chooser;
    // End of variables declaration//GEN-END:variables
}
