/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * grafLogin.java
 *
 * Created on 30/04/2012, 14:29:32
 */
package Igráfica;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import moveisdecor.Broadcast;
import moveisdecor.Login;
import moveisdecor.SolicitacaoUnicast;
import moveisdecor.Tabela;

/**
 *
 * @author Felipe
 */
public class grafLogin extends javax.swing.JFrame {

    Login log = new Login();
    Tabela tabela = new Tabela();
    private String login;
    private String senha;

    public grafLogin() {
        initComponents();
        setLocationRelativeTo(null); // Centraliza Janela
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        CampoLogin = new javax.swing.JFormattedTextField();
        entrar = new javax.swing.JButton();
        cadastrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CampoSenha = new javax.swing.JPasswordField();

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 246, 230));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 20));
        jLabel2.setText("Login:");

        CampoLogin.setFont(new java.awt.Font("Tahoma", 0, 18));

        entrar.setFont(new java.awt.Font("Tahoma", 0, 14));
        entrar.setText("Entrar");
        entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarActionPerformed(evt);
            }
        });

        cadastrar.setText("Cadastrar");
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel4.setText("Ainda não possui cadastro?");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Igráfica/novo.jpg"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 20));
        jLabel6.setText("Senha:");

        CampoSenha.setFont(new java.awt.Font("Tahoma", 0, 18));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CampoSenha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(70, 70, 70)
                            .addComponent(jLabel6))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(68, 68, 68)
                            .addComponent(entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(CampoLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)))
                .addGap(114, 114, 114))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jLabel2)
                .addContainerGap(190, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CampoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CampoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cadastrar)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarActionPerformed
        Thread t = new Thread(log);        //Cria a linha de execução
        t.start();                      //Ativa a thread
        Thread thrTab = new Thread(tabela); //thread da tabela
        thrTab.start();                 //ativa a thread da tabela

        // Pega dados do campo texto
        login = CampoLogin.getText();
        senha = CampoSenha.getText();

        log.setJanela(this);
        try {

            log.FLogin(login, senha); //passa o login e a senha digitadas

        } catch (Exception ex) {
            Logger.getLogger(grafLogin.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_entrarActionPerformed

    public void logar(boolean resp) {

        System.out.println(resp);
        if (resp == true) {
            ChatGlobal glob = null;

            try {

                Broadcast conversa = new Broadcast();
                conversa.entrarChatGlobal(); //entra no grupo do chat global

                Thread chat = new Thread(conversa);
                chat.start(); //thread para receber mensagens do broadcast
                
                
                SolicitacaoUnicast ouvirUnicast = new SolicitacaoUnicast(login, tabela);
                Thread t= new Thread(ouvirUnicast);//thread para escutar o unicast
                t.start();
                glob = new ChatGlobal(conversa, tabela, ouvirUnicast);
                conversa.setJanela(glob);
                glob.setLogin(login); //envia o login pra interface grafica
                

            } catch (Exception ex) {
                Logger.getLogger(grafLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
            glob.setName(); //seta o nome do usuário na janela do chat global
            glob.setVisible(true);
            // Se o login estiver correto IF
            this.setVisible(false);


        } else {

            JOptionPane.showMessageDialog(null, "Login ou senha errada. Tente Novamente!");

        }

    }

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        //deixa a interface grafica do cadastro visivel
        grafCadastro cad = new grafCadastro();
        cad.setVisible(true);
    }//GEN-LAST:event_cadastrarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField CampoLogin;
    private javax.swing.JPasswordField CampoSenha;
    private javax.swing.JButton cadastrar;
    private javax.swing.JButton entrar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
