/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Grupos.java
 *
 * Created on 08/05/2012, 01:01:35
 */
package Igráfica;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import moveisdecor.Multicast;
import moveisdecor.Multicast2;

public class Grupos extends javax.swing.JFrame {

    Multicast group = new Multicast();
    Multicast2 group2 = new Multicast2();
    
    /** Creates new form Grupos */
    public Grupos() {
        initComponents();
        setLocationRelativeTo(null); // Centraliza Janela
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        grupo1 = new javax.swing.JButton();
        grupo2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 246, 230));

        jLabel1.setFont(new java.awt.Font("Viner Hand ITC", 0, 48));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Igráfica/novo-2.jpg"))); // NOI18N

        grupo1.setText("Grupo 1");
        grupo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grupo1ActionPerformed(evt);
            }
        });

        grupo2.setText("Grupo 2");
        grupo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grupo2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(grupo2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(grupo1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(grupo1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(grupo2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void grupo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grupo1ActionPerformed
        ChatGrupo grupo1 = new ChatGrupo();
        grupo1.setVisible(true);

        try {
            group.entrarChatMulticast();
        } catch (IOException ex) {
            Logger.getLogger(Grupos.class.getName()).log(Level.SEVERE, null, ex);
        }
        Thread thr1 = new Thread(group);
            thr1.start();
    }//GEN-LAST:event_grupo1ActionPerformed

    private void grupo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grupo2ActionPerformed
        ChatGrupo grupo2 = new ChatGrupo();
        grupo2.setVisible(true);

        try {
            group2.entrarChatMulticast();
        } catch (IOException ex) {
            Logger.getLogger(Grupos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Thread thr2 = new Thread(group2);
            thr2.start();
    }//GEN-LAST:event_grupo2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void run() {
        new Grupos().setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton grupo1;
    private javax.swing.JButton grupo2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
